<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\rotovr\base.mtl" />
    <None Remove="assets\rotovr\base.obj" />
    <None Remove="assets\rotovr\chair.mtl" />
    <None Remove="assets\rotovr\chair.obj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\rotovr\base.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\rotovr\base.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\rotovr\chair.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\rotovr\chair.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="HelixToolkit.Core.Wpf" Version="2.27.1" />
    <PackageReference Include="HelixToolkit.SharpDX.Core" Version="2.27.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RotoGLBridge\RotoGLBridge.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\roto2\base.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\roto2\base.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\roto2\chair.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\roto2\chair.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  

</Project>
