<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<LangVersion>preview</LangVersion>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
    <Page Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="assets\rotovr\base.mtl" />
    <None Remove="assets\rotovr\base.obj" />
    <None Remove="assets\rotovr\chair.mtl" />
    <None Remove="assets\rotovr\chair.obj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\rotovr\base.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\rotovr\base.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\rotovr\chair.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\rotovr\chair.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="HelixToolkit.Core.Wpf" Version="2.27.3" />
    <PackageReference Include="HelixToolkit.SharpDX.Core" Version="2.27.3" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
	  <PackageReference Include="ScottPlot.WPF" Version="5.1.57" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RotoGLBridge\RotoGLBridge.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\roto2\base.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\roto2\base.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\roto2\chair.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\roto2\chair.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	<ItemGroup>
		<None Remove="**/*.bak" />
	</ItemGroup>
  

</Project>
