<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Configurations>Debug;Release;Dev</Configurations>
		<Platforms>AnyCPU;x64</Platforms>
		<VersionPrefix>0.0.10</VersionPrefix>
		<SharpieVersion>1.1.0</SharpieVersion>
		<Platform>x64</Platform>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Plugins\YawEmu\**" />
		<EmbeddedResource Remove="Plugins\YawEmu\**" />
		<None Remove="Plugins\YawEmu\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Plugins\Roto\RotoPlugin.cs" />
	  <Compile Remove="Scripts\Main.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Plugins\.gitignore" />
		<None Remove="Plugins\YawEmu.7z" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="Sharpie.Engine" Version="$(SharpieVersion)" />
		<PackageReference Include="Sharpie.Helpers.Core" Version="$(SharpieVersion)" />
		<PackageReference Include="Sharpie.Helpers.Telemetry" Version="$(SharpieVersion)" />
		<PackageReference Include="Sharpie.Plugins.Speech" Version="$(SharpieVersion)" />
		<PackageReference Include="Sharpie.Plugins.SharpDX" Version="$(SharpieVersion)" />
		<PackageReference Include="Sharpie.Plugins.UsbWatcher" Version="$(SharpieVersion)" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' != 'Release'">
		<ProjectReference Include="..\..\..\sharpie\src\Sharpie\Sharpie.Engine\Sharpie.Engine.csproj" />
		<ProjectReference Include="..\..\..\sharpie\src\Plugins\Sharpie.Plugins.Speech\Sharpie.Plugins.Speech.csproj" />
		<ProjectReference Include="..\..\..\sharpie\src\Sharpie\Sharpie.Helpers.Telemetry\Sharpie.Helpers.Telemetry.csproj" />
		<ProjectReference Include="..\..\..\sharpie\src\Sharpie\Sharpie.Helpers.Core\Sharpie.Helpers.Core.csproj" />
		<ProjectReference Include="..\..\..\sharpie\src\Plugins\Sharpie.Plugins.SharpDX\Sharpie.Plugins.SharpDX.csproj" />
		<ProjectReference Include="..\..\..\sharpie\src\Plugins\Sharpie.Plugins.UsbWatcher\Sharpie.Plugins.UsbWatcher.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="System.Reactive" Version="6.1.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\RotoUSB\rotoUSB.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="HIDApi.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
