<Project>
    <PropertyGroup>
        <Authors>Trevor (Drowhunter) Jones</Authors>
        <!-- <TargetFramework>net10.0</TargetFramework> -->
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
		<RepositoryUrl>https://github.com/drowhunter/roto-gamelink-bridge</RepositoryUrl>
        <PackageTags>Roto VR, GameLink</PackageTags>
    </PropertyGroup>
    <!-- <PropertyGroup Condition="'$(Configuration)' != 'Release'">
        <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    </PropertyGroup>     -->
</Project>